### ISSUE TITLE
Issue with AGP 8.0.0-alpha02 and R8

### ISSUE THREAD

**Issue by sproctor** [auth0/Auth0.Android#609]
### Describe the problem

R8 behavior seems to have changed with the new AGP version and things required by GSON used in Auth0 are being stripped out.

### What was the expected behavior?

App continue to function as with earlier versions of AGP.

### Reproduction

I believe the line causing the crash is: https://github.com/auth0/Auth0.Android/blob/62dd0ed5382607b44907e940de96b84cf97ddc45/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L169

### Environment

- **Version of this library used:** 2.8.0

```
buildTypes {
    getByName("release") {
        isMinifyEnabled = true
        isShrinkResources = true
    }
}
```

### Workaround

Add the following to proguard-rules.pro

```
-keepattributes Signature
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
-if class *
-keepclasseswithmembers class <1> {
  <init>(...);
  @com.google.gson.annotations.SerializedName <fields>;
}
```

**Comment by poovamraj** [comment]
Hi @sproctor, I tried this using our sample repository - https://github.com/auth0-samples/auth0-android-sample

I used this version of Android Studio - Android Studio Flamingo | 2022.2.1 Canary 4

The gradle plugin wrapper is 
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-milestone-2-all.zip
```

And the Gradle library version is

```
classpath 'com.android.tools.build:gradle:8.0.0-alpha04'
```

Since it is in Alpha, I guess the issue was fixed in the later versions. Can you verify this on your end as well?

**Comment by poovamraj** [comment]
Hey @sproctor, hope the above solution helps. We will close this issue for now but please feel free to reopen it if you have more doubts.

**Comment by sproctor** [comment]
I'm still seeing this with 8.0.0-alpha05. It's also reproducible by adding `android.enableR8.fullMode=true` to the `gradle.properties` file. This isn't reproducible in the sample because the sample doesn't use `SecureCredentialsManager`.
